version: "3"

services:
   backend:
      build: ./backend
   frontend:
      build: ./frontend
      depends_on:
      - backend
      volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/site:/usr/share/nginx/html
      - ./dh-param/dhparams.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/uss-hopper.site/fullchain.pem:/etc/letsencrypt/live/uss-hopper.site/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/uss-hopper.site/privkey.pem:/etc/letsencrypt/live/uss-hopper.site/privkey.pem

      ports:
      - 80:80
      - 443:443
